---
- name: Upgrade PAN-OS Standalone Firewall Within Same Train
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Download PAN-OS Software Version Within Same Train
      paloaltonetworks.panos.panos_software:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ api }}"
        version: "{{ software_version }}"
        download: yes
      register: download_status
    - name: Install PAN-OS Software Version Within Same Train
      paloaltonetworks.panos.panos_software:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ api }}"
        version: "{{ software_version }}"
        install: yes
      when: download_status.changed
      register: install_status
    - name: Reboot Standalone Firewall To Complete Upgrade Within Same Train
      paloaltonetworks.panos.panos_restart:
        provider:
          ip_address: "{{ ip_address }}"
          api_key: "{{ api }}"
      when: install_status.changed

 
